version: '2'
services:
  web:
    image: dockercloud/hello-world
    ports:
      - 8080
    networks:
      - front-tier
      - back-tier

  lb:
    image: dockercloud/haproxy
    ports:
      - 80:80
    links:
      - web
    networks:
      - front-tier
      - back-tier
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 

  command-service:
    container_name: command_service
    restart: unless-stopped
    build: 
      context: ./command-service
    ports:
      - 3000:3000
    links:
      - mongo-command
      - kafka

  kafka:
    image: spotify/kafka
    container_name: kafka
    restart: unless-stopped
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      ADVERTISED_PORT: 9092
      ADVERTISED_HOST: kafka

  mongo-command:
    image: mongo
    container_name: mongo-command
    restart: unless-stopped
    ports:
      - "27017:27017"

  mongo-query:
    image: mongo
    container_name: mongo-query
    restart: unless-stopped
    ports:
      - "27018:27017"

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge